/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEndScreens;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author glassiron
 */
public class SubjectFrntScrn extends javax.swing.JFrame {

    /**
     * Creates new form SubjectFrntScrn
     */
    public SubjectFrntScrn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        subjectScrollScreenAssignments = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        subjectScreenBackButton = new javax.swing.JButton();
        jcmbSubjectList = new javax.swing.JComboBox<>();
        btnSubjectAdd = new javax.swing.JButton();
        btnAssignmentAdd = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectScreenBackButton.setText("<-");
        subjectScreenBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectScreenBackButtonActionPerformed(evt);
            }
        });

        jcmbSubjectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcmbSubjectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcmbSubjectListMouseClicked(evt);
            }
        });
        jcmbSubjectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbSubjectListActionPerformed(evt);
            }
        });

        btnSubjectAdd.setText("+");
        btnSubjectAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectAddActionPerformed(evt);
            }
        });

        btnAssignmentAdd.setText("Add Assignment");
        btnAssignmentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jcmbSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubjectAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subjectScreenBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnAssignmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subjectScreenBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignmentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubjectAdd)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbSubjectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbSubjectListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbSubjectListActionPerformed

    private void btnSubjectAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectAddActionPerformed
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectAdd().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnSubjectAddActionPerformed

    private void jcmbSubjectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmbSubjectListMouseClicked
        
        String n = "";
        try {
            File read = new File("SubjectsData.txt");
            Scanner file = new Scanner(read);
            
            int f = jcmbSubjectList.getItemCount();
            String[] items = null;
            for (int i = 0; i < f; i++) {
                String spon = jcmbSubjectList.getItemAt(i);
                items[i] = spon;
                
            }
             
            
            while(file.hasNext()){
                //this is gionna say taht a subject exists every time its ran but it will add any new ones taht have been added to file
                String list = file.nextLine();
                String[] details = list.split("#");
                n = details[0];
                
                for (int i = 0; i < f; i++) {
                    if(n.equals(items[i])){
                        JOptionPane.showMessageDialog(null, "This subject already exists");
                    } else {
                        jcmbSubjectList.addItem(n);
                    }
                }
                
                
                
                file.close();
            }
            
        } catch (FileNotFoundException ex) {
        }
        
        jcmbSubjectList.addItem(n);
    }//GEN-LAST:event_jcmbSubjectListMouseClicked

    private void subjectScreenBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectScreenBackButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPageLog_Sign_in_etc().setVisible(true);
            }
        });
    }//GEN-LAST:event_subjectScreenBackButtonActionPerformed

    private void btnAssignmentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentAddActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentAdd().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAssignmentAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectFrntScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectFrntScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectFrntScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectFrntScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectFrntScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignmentAdd;
    private javax.swing.JButton btnSubjectAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcmbSubjectList;
    private javax.swing.JButton subjectScreenBackButton;
    private javax.swing.JScrollPane subjectScrollScreenAssignments;
    // End of variables declaration//GEN-END:variables
}
